addons/block_code/block_code_node/block_code.gd
addons/block_code/block_code_node/utilities/signal_manager.gd
addons/block_code/types/types.gd
addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/statement_block/statement_block.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.tscn
addons/block_code/ui/picker/categories/category_factory.gd
test_game/test_game.tscn

Added blocks for node/group stuff and changed existing signal block to signal to a group instead of all nodes. We can change the name to "call" instead of "signal" if we want, but since the user doesn't actually implement their own functions yet, it didn't really make sense to change "on signal" to "on call".
I also made the styling a bit better and added an `if` block without the `else`. You can see an example of the new stuff in the `Manuel` block script lol. Next thing to add can be a simple `Area2D` node that actually generates this `on_body_enter` event.

Added group blocks

---

addons/block_code/types/types.gd
addons/block_code/ui/blocks/basic_block/basic_block.tscn
addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/parameter_block/parameter_block.gd
addons/block_code/ui/blocks/parameter_block/parameter_block.tscn
addons/block_code/ui/blocks/statement_block/statement_block.tscn
addons/block_code/ui/blocks/utilities/background/background.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/picker/categories/category_factory.gd
addons/block_code/ui/picker/picker.gd
test_game/test_game.tscn

This adds a way to add custom blocks to a specific built-in class. You can either expose a property (given it's `Variant.Type` can match a `Types.BlockType`), or create a custom block for more control. See `get_built_in_categories()` in `CategoryFactory`.
You can find an example of this for `Node2D` in test scene.
Something to think about at some point is how we can define our types better. Should we have a `NUMBER` type that allows for integer and float input? And do we need a way to have type inheritance, such that we could keep the `INT` and `FLOAT` types, but they are still a `NUMBER`? I think defining our own types is a fine thing to do, as we want to add a layer of abstraction.
I also made the styling a bit nicer, LMK if you don't like it. Essentially just gave the blocks a bit more …

Blocks for built-ins

---

addons/block_code/ui/block_canvas/node_block_canvas/node_block_canvas.gd
addons/block_code/ui/blocks/entry_block/entry_block.gd
addons/block_code/ui/blocks/entry_block/entry_block.tscn
addons/block_code/ui/blocks/parameter_block/parameter_block.tscn
addons/block_code/ui/picker/categories/category_factory.gd
test_game/test_game.tscn

This felt like a good addition to have, since before the script generator was looking for a `block_name` for entry blocks, and generating the code itself, but now it asks the `EntryBlock` for the code, and appends it to the script that way.
`EntryBlock` inherits from `StatementBlock` (both scene and script), utilizing the statement block to generate the parameters UI programatically. This way we can expose things like signals by automatically creating an `EntryBlock` for them.
Originally we had been using `BasicBlock` as a template for entry blocks, but it is much nicer to have an `EntryBlock` that can actually generate a method signature.

Add EntryBlock class

---

addons/block_code/types/types.gd
addons/block_code/ui/bsd_templates/default_blocktrees.tres
addons/block_code/ui/picker/categories/category_factory.gd
test_game/test_game.tscn

Added logic blocks, loop blocks, queue_free() block, and exposes some RigidBody2D physics properties.
See test game scene for example scripts.

More blocks

---

addons/block_code/ui/main_panel.tscn

…relabelling it from “Test” to “Print Generated Script” in the process.
This saves vertical space & looks better.
| Before | After |
| ------ | ----- |
| ![Screenshot from 2024-06-14 14-27-10](https://github.com/endlessm/block-programming-plugin/assets/86760/99f92e86-af46-4056-a704-bf26baa27708) | ![Screenshot from 2024-06-14 14-26-24](https://github.com/endlessm/block-programming-plugin/assets/86760/d2fc46a2-22e9-44b7-b09f-7c9c261fdf2d) |

main_panel: Move “Print Script” button to titlebar

---

addons/block_code/block_code_plugin.gd
addons/block_code/drag_manager/drag_manager.gd
addons/block_code/types/types.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd

This adds type casting to blocks. So if there is a defined way to cast from `INT` to `STRING`, you can snap an `INT` block to a `STRING` block, for example if you wanted to print out a math expression. The program will find the shortest way to convert an `INT` to a `STRING` and it will be added to the generated code.
I think this is nicer than having to do some sort of inheritance where we have a `NUMBER` class etc. Let me know what you think!

Type casting

---

addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/block_canvas/serialized_block.gd
addons/block_code/ui/blocks/basic_block/basic_block.gd
addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/entry_block/entry_block.gd
addons/block_code/ui/blocks/parameter_block/parameter_block.gd
addons/block_code/ui/blocks/statement_block/statement_block.gd
addons/block_code/ui/bsd_templates/default_blocktrees.tres
test_game/test_game.tscn

Use the block class in the resources instead of the scene path. This decouples the block data from the block UI. Refactoring the scenes shouldn't break the block data.

Block resources: Dehardcode scene paths

---

addons/block_code/instruction_tree/instruction_tree.gd

This method was introduced in 0b392c281a31d7f41031674debe7cc06e949fff5 but never used.

instruction_tree: Remove unused generate_tree() method

---

addons/block_code/block_code_plugin.gd

By default, when a node is selected, Godot shows the 2D or 3D editor corresponding to the selected node type. Showing the Block Code editor when a BlockCode node is selected will make the flow of the editor easier to understand.

Show Block Code editor when BlockCode node is selected

---

addons/block_code/instruction_tree/instruction_tree.gd

I think this is clearer than using instance variables, which persist beyond the call to generate_text, to store state which is transient to any given call to generate_text. It's also shorter!

instruction_tree: Pass depth & output buffer as parameters

---

addons/block_code/drag_manager/drag_manager.gd
addons/block_code/types/types.gd
addons/block_code/ui/blocks/entry_block/entry_block.gd
addons/block_code/ui/blocks/entry_block/entry_block.tscn
addons/block_code/ui/blocks/parameter_block/parameter_block.gd
addons/block_code/ui/blocks/statement_block/statement_block.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/blocks/utilities/snap_point/snap_point.gd
addons/block_code/ui/constants.gd
addons/block_code/ui/picker/categories/category_factory.gd
test_game/test_game.tscn

And use Variant.Type enum for the Value block variant.
This means we stick to GDScript variants for the values represented by Value blocks:
- A constant like "viewport width"
- A property like "rotation"
- A parameter like A in "A + B"
- The resulting value of "A + B"
The slots that can contain Value blocks also have a matching variant type now.
Unfortunately there is no way to convert the native Variant.Type enum to string, so still we need dictionaries to go back and forth the string formatting.
Previously there was a custom NODE type, although unused. This is now replaced by NODE_PATH, which is the same thing that Godot does in the PackedScene resource when exporting a property of type Node.
Also: improve readability of drag manager and use a constant for the minimum slot distance.

Decouple block type from block variant

---

pong_game/ball_spawn_area.tscn
pong_game/goal_area.tscn
pong_game/pong_game.tscn

- Pong demo: Add area for spawning balls
- Pong demo: Add areas for goals
https://phabricator.endlessm.com/T35504

Pong areas

---

addons/block_code/block_code_plugin.gd
addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/block_canvas/block_canvas.tscn
addons/block_code/ui/main_panel.gd
addons/block_code/ui/picker/picker.gd
addons/block_code/ui/title_bar/title_bar.gd
addons/block_code/ui/title_bar/title_bar.tscn

https://phabricator.endlessm.com/T35511
-----
In the BlockCode editor, this replaces the label displaying the current node type with a dropdown menu that allows the user to switch between all the BlockCode nodes in a scene:
In addition, it adds two different empty states for the Block Code editor, when there are no BlockCode nodes in the scene, or when no BlockCode node is selected:

Add a widget to switch between BlockCode nodes

---

addons/block_code/block_code_node/block_code.gd
addons/block_code/ui/main_panel.gd
addons/block_code/ui/title_bar/title_bar.gd
pong_game/pong_game.tscn
test_game/test_game.tscn

This is user facing in the Inspector. Exported properties appear capitalized in the Inspector so this will now figure as "Block Script" rather than "Bsd"

BlockCode node: Rename bsd to block_script

---

addons/block_code/ui/main_panel.gd

In 60e74e9a1ba00c7cf5d4ad91c8eb6ad815737ffb, MainPanel.switch_script was changed to update UI elements even if the block_code node is null, but it also switching to the Block Code tab in the editor in either case.
https://phabricator.endlessm.com/T35511

Only show Block Code tab if a BlockCode node is selected

---

addons/block_code/ui/block_canvas/node_block_canvas/node_block_canvas.gd
addons/block_code/ui/blocks/entry_block/entry_block.gd
addons/block_code/ui/blocks/parameter_block/parameter_block.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/picker/categories/category_factory.gd

The block ‘compiles’ to a callback function, which needs to be connected
to the signal in question. To do this, add an additional code-generation
step that generates an _init() function to connect signals.
A more idiomatic approach would be to connect to the signals in the
_ready() function. This would involve merging additional code with the
user-supplied _ready() function, so is deferred for now. _init() works
fine.
https://phabricator.endlessm.com/T35510

Add ‘On body entered’ entry block for Area2D and RigidBody2D

---

pong_game/ball.tscn

In moddable pong the project had linear damp and angular damp in zero. To do that only for the ball (not project wide) we can set linear and angular damp mode to "replace" in the RigidBody2D.
https://phabricator.endlessm.com/T35504

Pong demo: Fix ball velocity decay

---

addons/block_code/simple_nodes/simple_character/simple_character.gd
addons/block_code/ui/picker/picker.gd

This is just a really small fix for an error that was happening in the pong game. For previous classes with custom blocks, like `SimpleCharacter`, you had to define a method that specified the base class so the picker would know which blocks to populate itself with.
However, there is a function `script.get_instance_base_type()` that gets this automatically from whichever class the script extends. Much nicer than having to define a function for this every time.

Fix base class identification (for Picker)

---

addons/block_code/ui/picker/categories/category_factory.gd
pong_game/ball.tscn
pong_game/pong_game.tscn
pong_game/space.tscn
test_game/test_game.tscn

The new generated AudioStreamPlayer was held by a local variable, then added as a child of the node originally.
It is okay for only one AudioStreamPlayer in the node. However, some nodes may have mulitiple AudioStreamPlayers, then the local variable from the code blocks will be conflicted, due to the same variable name.
Therefore, store the AudioStreamPlayer into the node's global VAR_DICT with a key passed from the parameter "name" directly. This also avoids searching in the node tree.
https://phabricator.endlessm.com/T35501

block_code/picker: Store the AudioStreamPlayer in the VAR_DICT

---

addons/block_code/README.md

This section of documentation explains how to set up and begin using the plugin.
We should add the AssetLib link once it exists!

Add getting started section to README

---

addons/block_code/examples/pong_game/paddle.gd
addons/block_code/examples/pong_game/pong_game.gd
addons/block_code/simple_nodes/simple_character/simple_character.gd
addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/picker/categories/block_category.gd
addons/block_code/ui/picker/categories/category_factory.gd
addons/block_code/ui/picker/picker.gd
docs/OVERVIEW.md
tests/test_category_factory.gd

This reworks the block category handling to (hopefully) make it more flexible and intuitive. The primary changes are:
* Store the desired category as a property of the block and then generate the categories from one big list of blocks. This is very much internal, but it allows defining blocks pretty much arbitrarily while maintaining the desired grouping. Previously you added categories and there was a process to merge duplicate categories. The end result is the same but I think this is a bit clearer and more efficient. This is [block: Make category a property of Block](https://github.com/endlessm/godot-block-coding/commit/115c92b46b2883f8c65ff5340feed32713de4dfa). It also adds an `order` property for categories so that you can take the arbitrary block list, group them into categories, …

Categories rework

---

.github/workflows/godot-asset-library.yaml

The workflow is triggered by publishing a release (which is essentially
a fancy tag). If it turns out we need to trigger it manually we could
later add workflow_dispatch.
https://phabricator.endlessm.com/T35503

github: Add workflow to publish to Asset Library

---

.github/workflows/godot-asset-library.yaml

Now that the plugin has been accepted, it appears the ID is 3095 per https://godotengine.org/asset-library/asset/3095. I guess the previous ID was just for the submission.
https://phabricator.endlessm.com/T35503

github: Update Asset Library ID

---

addons/block_code/block_code_node/utilities/signal_manager.gd
addons/block_code/ui/picker/categories/category_factory.gd

In #60, I wasn't a fan of us needing to reset _all_ of the ball nodes when a player scores, so I'm proposing a "send signal to node" block. This requires a little bit of tweaking so we aren't defining `var signal_manager` in either of the send signal blocks, which makes it possible to include multiple of them in the same context.

Add a "Send signal to node" block

---

addons/block_code/ui/block_canvas/node_block_canvas/node_block_canvas.gd

Forgot to commit this in #70 :)

Clean up redundant code with multiple entry blocks

---

addons/block_code/drag_manager/drag_manager.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.tscn
addons/block_code/ui/blocks/utilities/snap_point/snap_point.gd

https://phabricator.endlessm.com/T35519

Re-order blocks when a block is placed in an occupied snap point

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/public.yml

Addressing something @dylanmccall [brought up](https://endlessos.slack.com/archives/C0540FJT73J/p1718990948525819), this PR:
- Disables blank (formless) issues
- Directs EOSF employees to Phabricator
- Adds a form for public issue reports
If there's other useful info to add to the public form we can always iterate on it.

Issue templates

---

addons/block_code/examples/pong_game/pong_game.tscn

The Godot project size defaults to 1152x648 which is 60% of the viewport in Pong. So adding a camera with 0.6 zoom makes the game fit in the default viewport. And makes it look odd in other sizes.
Also now the HUD layer follows the viewport size.
https://phabricator.endlessm.com/T35515

Add camera to fit default project size

---

addons/block_code/ui/picker/categories/block_category_display.gd
addons/block_code/ui/picker/categories/block_category_display.tscn

When all the categories are shown, you may need to do quite a bit of scrolling to find the block you want or just to discover what's there. This changes the category display so that each category is a button that can show or hide its blocks. All blocks are initially hidden to be able to see all the available categories.
The expander is implemented as a flat button with a triangle icon. The icon comes from an atlas with two states corresponded to expanded or unexpanded. Godot does provide the Tree class with similar functionality, but it's a bit complex to use. More importantly TreeItems are their own class that don't derive from Node. That would break the current Block usage.
The SVG with the triangle drawings is included should any editing be needed, but it's not used in the scene. …

block_category_display: Make categories buttons to show/hide blocks

---

addons/block_code/drag_manager/drag_manager.gd
addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/blocks/utilities/drag_drop_area/drag_drop_area.gd
addons/block_code/ui/blocks/utilities/drag_drop_area/drag_drop_area.tscn
addons/block_code/ui/blocks/utilities/snap_point/snap_point.gd

This addresses a bunch of little things related to drag and drop in the editor. Importantly, I fixed two small bugs that occur when snapped nodes are separated from each other. There's also a bit of code cleanup, originally inspired by `previewing_snap_point` and `preview_block` in `DragManager` not being in sync with each other. In the end, I put those concepts into a separate `DragManager.Drag` class which manages a single drag & drop operation. That also provided a way to better organize our code related to filtering and sorting snap points, now using the stuff built in to `Array`.
I also ended up adding a change related to https://phabricator.endlessm.com/T35525, making a block fade out slightly if it is going to be deleted.
-----
https://phabricator.endlessm.com/T35524

Reset snap point variables in DragManager.drag_end

---

.github/workflows/godot-asset-library.yaml

Current publish job is only triggered by published release. But, it is guarded by "released" action. The mismatched condition blocks the jobs. Drop the publish job's action type check to avoid this issue.

github: Drop the publish job's action type check

---

addons/block_code/drag_manager/drag_manager.gd
addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/blocks/block/block.gd

Made it so that parameter blocks copy-dragged from an `EntryBlock` can only be placed below entry blocks with the same method signature.
Also darken the block trees that cannot be snapped to by the current dragged block.
https://phabricator.endlessm.com/T35521

Add scope to blocks

---

.gitattributes
addons/block_code/plugin.cfg

These are shown in the plugins section of the project settings.
The author and description fields can be populated statically, but the version number cannot unless we manually update it for each release. Instead, lean on a feature of `git archive` where magic placeholders in specified files can be substituted for strings based on the current commit, crucially including the output of `git describe` which will return a tag name if the current commit is an annotated tag.
v0.2.0 is annotated while v0.1.0 was not.
https://phabricator.endlessm.com/T35503

Populate more fields of plugin.cfg

---

addons/block_code/ui/picker/categories/category_factory.gd

So they start at 10 and are separated by 10. Also 2 categories were sharing the same
number by mistake.
https://phabricator.endlessm.com/T35507

Update index number for categories order

---

addons/block_code/block_code_node/block_code.gd
addons/block_code/simple_nodes/simple_character/simple_character.gd

Any Simple node like `SimpleCharacter` will have its `_ready` overwritten by the block script if a ready block exists. This PR enables setup for the Simple node to still happen regardless. (e.g. Pong paddle texture initialization)
This was the best way I could find to do this. Calling `super()` in the child `_ready` when `_ready` is not overridden in the parent causes an error (even though it's a virtual method...). I don't know of any way to check if the method is overridden in the parent to call it or not.

Fix Simple node setup not happening

---

tests/test_category_factory.gd

Otherwise the test prints warnings about a pile of orphans.
https://phabricator.endlessm.com/T35520

test_category_factory: Free Block nodes

---

.github/workflows/godot-asset-library.yaml

The referenced commit is the merge of these two PRs:
https://github.com/deep-entertainment/godot-asset-lib-action/pull/2
https://github.com/deep-entertainment/godot-asset-lib-action/pull/3
https://phabricator.endlessm.com/T35503

ci: Use my fork of godot-asset-lib-action

---

addons/block_code/README.md

https://phabricator.endlessm.com/T35508

tests: Document using the GUT CLI

---

addons/block_code/examples/pong_game/pong_game.tscn
addons/block_code/ui/picker/categories/category_factory.gd
tests/test_category_factory.gd

To integer blocks for the viewport width and height. And one Vecto2 block for the viewport center.

Add viewport value blocks

---

addons/block_code/drag_manager/drag_manager.gd
addons/block_code/examples/pong_game/pong_game.tscn
addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/entry_block/entry_block.tscn
addons/block_code/ui/blocks/statement_block/statement_block.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/blocks/utilities/parameter_output/parameter_output.gd
addons/block_code/ui/blocks/utilities/parameter_output/parameter_output.tscn
addons/block_code/ui/blocks/utilities/snap_point/snap_point.gd
addons/block_code/ui/blocks/utilities/snap_point/snap_point.tscn

This resolves an error that occurred when a block which provides a parameter block was spawning multiple child blocks. Instead of that logic being provided by DragManager, this commit adds a ParameterOutput node which ensures its associated SnapPoint always has a child node, and propagates `drag_started` signals up from the child block to the parent block.
https://phabricator.endlessm.com/T35531

Add ParameterOutput and monitor node children in SnapPoint

---

addons/block_code/ui/picker/categories/category_factory.gd

Calling ``InputMap.load_from_project_settings()`` in ``addons/block_code/ui/picker/categories/category_factory.gd`` in the editor causes all spatial_editor actions to be lost, making it impossible to use first person camera controls in the 3D tab.
This pull request fixes https://github.com/endlessm/godot-block-coding/issues/100 by re-adding all spatial_editor actions after calling ``InputMap.load_from_project_settings()`` and after adding all the Input actions to ``block_list``, making sure they don't appear in the input blocks.

Fix InputMap load removing spatial_editor actions in editor

---

addons/block_code/README.md

The getting started instructions imply that you need to clone the repository as a final step to install the plugin which is not the case! Also add a note for those wanting to work in the repo.

Fix getting started instructions

---

addons/block_code/block_code_plugin.gd
addons/block_code/ui/main_panel.gd
addons/block_code/ui/main_panel.tscn
addons/block_code/ui/picker/categories/block_category_button.gd
addons/block_code/ui/picker/categories/block_category_button.tscn
addons/block_code/ui/picker/categories/block_category_display.gd
addons/block_code/ui/picker/categories/block_category_display.tscn
addons/block_code/ui/picker/picker.gd
addons/block_code/ui/picker/picker.tscn

This adds all uncollapsed block categories back into one large scroll container, but now with buttons that can navigate to each category. This allows the user to see the entire selection of blocks, without the tedium of scrolling. I think this will be nicer for adding in a little menu to create variables within the scrollbox as well.
https://phabricator.endlessm.com/T35532

Scratch-like category UI

---

addons/block_code/plugin.cfg

By default, `git describe` (which is what backs this
`$Format:%(describe)$` placeholder) only uses annotated tags to
construct a version number.
However I have just discovered that if you use the GitHub web interface
to create a tag as part of making a release, the resulting tag is
lightweight, not annotated. As a result the 0.4.0 release describes its
version as `v0.3.1-27-ga9a2ee9`.
Update the placeholder to (the equivalent of) `git describe --tags`,
which considers lightweight tags as well as annotated tags.

plugin.cfg: Use lightweight tags to determine version

---

addons/block_code/ui/main_panel.tscn

The tooltip previously claimed that the shortcut was Ctrl + Space, but in fact it is Ctrl + Backslash.
Fix this error; and adjust the tooltip style to match the tooltip on the equivalent button in the script editor view. I personally don't like the camel-casing of BackSlash but that's what Godot calls that key.
https://phabricator.endlessm.com/T35540

main_panel: Correct tooltip for block picker toggle button

---

addons/block_code/ui/blocks/utilities/background/background.gd

Setting outline_color queues a redraw, so setting it in the draw handler implies that it will queue infinite redraws. In Godot 4.2 this doesn't happen, but in Godot 4.3 it does and causes the editor to lock up until it finally crashes.
I don't know if it's a bug in one version or the other, but either way we don't need to do that. If outline_color is already set based on the color, then set it at the time color is set and stop exporting it since any user provided value would be ignored.
https://phabricator.endlessm.com/T35494

background: Avoid infinite draw cycle

---

addons/block_code/ui/picker/categories/category_factory.gd

In Godot 4.2.1, a static function used as a Callable from a static function fails to be resolved. This causes the following error in our case:
```
res://addons/block_code/ui/picker/categories/category_factory.gd:109 -
Invalid get index '_category_cmp' (on base: 'Nil')
```
See https://github.com/godotengine/godot/issues/86032 for details. This can be worked around by using the fully qualified class method name.
Fixes: #94

category_factory: Fix static Callable use in Godot 4.2.1

---

addons/block_code/simple_nodes/simple_character/simple_character.gd

Add 2 methods and call them, instead of having the implementation in the code template ("statement" property).
This improves a bit when serializing the implementation. But most importantly, allows the 2 blocks to be added to the same node without a collision on the var dir being declared twice.

SimpleCharacter: Use methods for player movement

---

addons/block_code/block_code_node/block_code.gd

This adds some new warnings to `BlockCode` to deal with common problems users may encounter:
Note that the "parent should only contain on BlockCode" warning also occurs when the parent is a separate (instantiated) scene. I simulated that in the screenshot by adding a `BlockCode` node to space.tscn, so in pong_game.tscn, where I added another `BlockCode` under `Space`, we get a warning.

Add blockcode warnings

---

addons/block_code/ui/picker/categories/category_factory.gd

- Play (ahead/backwards)
- Pause
- Stop
- is playing?
https://phabricator.endlessm.com/T35543

Add blocks for AnimationPlayer

---

addons/block_code/block_code_plugin.gd
addons/block_code/ui/main_panel.gd
addons/block_code/ui/title_bar/title_bar.gd

https://phabricator.endlessm.com/T35541

T35541 cleanups

---

addons/block_code/block_script_data/block_script_data.gd
addons/block_code/ui/constants.gd
addons/block_code/ui/main_panel.gd

https://phabricator.endlessm.com/T35547

Add version to block script data

---

addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/control_block/control_block.tscn
addons/block_code/ui/blocks/statement_block/statement_block.tscn
addons/block_code/ui/blocks/utilities/snap_point/snap_point.tscn

Certain components inside our Block scenes were consuming input events, making it difficult to interact with other blocks positioned around them.

Set MOUSE_FILTER_IGNORE for blocks where necessary

---

addons/block_code/block_code_plugin.gd
addons/block_code/block_script_data/block_script_data.gd
addons/block_code/examples/pong_game/pong_game.tscn
addons/block_code/instruction_tree/instruction_tree.gd
addons/block_code/types/types.gd
addons/block_code/ui/block_canvas/node_block_canvas/node_block_canvas.gd
addons/block_code/ui/block_canvas/variable_resource.gd
addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/parameter_block/parameter_block.gd
addons/block_code/ui/blocks/statement_block/statement_block.gd
addons/block_code/ui/main_panel.gd
addons/block_code/ui/picker/categories/category_factory.gd
addons/block_code/ui/picker/categories/variable_category/create_variable_button.gd
addons/block_code/ui/picker/categories/variable_category/create_variable_button.tscn
addons/block_code/ui/picker/categories/variable_category/create_variable_dialog.gd
addons/block_code/ui/picker/categories/variable_category/create_variable_dialog.tscn
addons/block_code/ui/picker/categories/variable_category/variable_category_display.gd
addons/block_code/ui/picker/categories/variable_category/variable_category_display.tscn
addons/block_code/ui/picker/picker.gd

This removes the old variable system we had with the VAR_DICT, and replaces it with a menu for creating typed variables that you can use as blocks.
Side note: We will need to fix the sound blocks after this is merged, since they use the VAR_DICT. I think it would be good to have some library functions or a singleton our blocks can call on for more behavior like this.
https://phabricator.endlessm.com/T35535

Revamp variable system

---

addons/block_code/ui/blocks/block/block.gd

The to_string implementation for Block follows the same pattern as the default for Godot objects, but it uses get_block_class and includes the block_name property for each block. This will make it easier to differentiate between different blocks while debugging the block code editor.
-----
This is inspired by #132, where we add block_name for all of the blocks.

Add _to_string for Block

---

.github/workflows/checks.yaml

This fixes the following warning that was previously seen on every run of the checks workflow:
> Warning: Neither 'python-version' nor 'python-version-file' inputs were supplied. Attempting to find '.python-version' file.
> Warning: .python-version doesn't exist.
> Warning: The `python-version` input is not set.  The version of Python currently in `PATH` will be used.
Python 3.11 happens to be what is in Endless OS 6.

ci: Set Python version for setup-python

---

addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/picker/categories/category_factory.gd
addons/block_code/ui/tooltip/tooltip.gd
addons/block_code/ui/tooltip/tooltip.tscn

This overrides the tooltip of all blocks to be a custom control (a thin wrapper around RichTextLabel) and adds a couple of new tooltips that take advantage of this:
I don't want to spend too much time on the tooltips themselves because we intend to review the wording of the blocks themselves & terminology used in conjuction with the learning team – and potentially changing the level of abstraction of some of the blocks. Similarly I could imagine making the tooltips fancier by, for example, listing the parameters, adding a note about what kind of block it is, etc. But again I think this would be better done in conjuction with the learning team. So here I'm focusing on just having the capability to use rich text in tooltips.
https://phabricator.endlessm.com/T35540

Add rich-text tooltips for blocks

---

addons/block_code/examples/pong_game/pong_game.tscn

This appears to have been broken in 031b29e. In GoalAreaLeft, the checked group was changed from balls to walls. In GoalAreaRight, the checked group was changed from balls to the empty string.

Pong: Fix scoring

---

addons/block_code/block_code_node/block_code.gd
addons/block_code/block_code_plugin.gd
addons/block_code/inspector_plugin/block_script_inspector.gd
addons/block_code/ui/picker/categories/block_category.gd

Some memory leak fixes I found looking at the Godot stdout. After this I get no more warnings about leaked objects in the tests or with minimal usage.

Leak fixes

---

addons/block_code/ui/blocks/parameter_block/parameter_block.tscn
addons/block_code/ui/picker/categories/block_category_button.tscn

This partially reverts commit 1b6d64b4f6d532139e29acb0d1cf9c4824ac9ced (“Don't recreate resources when editing plugin scenes”).
I incorrectly believed that these were being fully recreated every time the scene is instantiated based on another element's stylebox, but in fact they are being used as a template and it is only the colour that is being adjusted.
See discussion at https://github.com/endlessm/godot-block-coding/pull/138#discussion_r1681557942.

Reinstate stylebox overrides

---

addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/main_panel.gd

Add a resource property to blocks of type SerializedBlock. The resource will be updated before building the tree.
This mitigates having a huge diff in scenes with blocks for minimum changes like moving a block in the canvas.
https://phabricator.endlessm.com/T35565

Serialization: Reuse SerializedBlock resources

---

addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.tscn

Previously any text change was sending the modified signal, adding too many actions to the undo/redo history (one per typed character). This was also capturing shortcuts like Ctrl-Z for undoing and sending the modified signal, thus piling to the history, not going back.
Instead, send the modified signal when the line edit is submitted (enter key pressed) or when it loses focus and the text has changed.
https://phabricator.endlessm.com/T35566

Parameter input: change text modification logic

---

addons/block_code/block_code_plugin.gd

In dbd7643, an early return was added to avoid updating the UI when the same BlockCode node has been selected. When a non-BlockCode has been selected, the main panel needs to be told about it so that it can show some friendly messages about adding a BlockCode node. However, any non-BlockCode node is represented as null, which means that changes to a selected non-BlockCode node can't be differentiated. Skip the early return in that case.
https://phabricator.endlessm.com/T35572

Plugin: Only skip duplicate work when BlockCode nodes selected

---

addons/block_code/ui/block_canvas/block_canvas.gd

Prior to 01ab76c, the block trees array was modified in place, which meant is was correctly typed as `Array[SerializedBlockTreeNode]`. Now it's being built from an untyped array, which breaks script generation.
https://phabricator.endlessm.com/T35573

BlockCanvas: Fix block node array typing

---

addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/blocks/control_block/control_block.tscn
addons/block_code/ui/blocks/statement_block/statement_block.tscn

This reverts commit 6a11ebe7a1ee66ebdbbfda4eec21c37c179ab079.
https://phabricator.endlessm.com/T35573

Revert "Block: Handle bottom_snap property directly"

---

addons/block_code/ui/blocks/block/block.gd

Add a setter for bottom_snap_path so that bottom_snap can be set immediately without waiting for the node to become ready. This simplifies testing as the Block doesn't need to be added to a scene to work correctly.
https://phabricator.endlessm.com/T35573

Block: Add setter to manage bottom_snap

---

.github/workflows/godot-asset-library.yaml

All my PRs were merged & released so this is equivalent to the version we have been using from my fork.

ci: Use asset lib action 0.6.0

---

addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/picker/categories/category_factory.gd

Add validation for the input text, and default values for blocks. Goal is to prevent generated code with syntax errors. It also improves the UX.
https://phabricator.endlessm.com/T35562

Text validation

---

addons/block_code/ui/util.gd

When switching to a different scene in the editor, the previous edited scene root will no longer have a parent and you'll see a pile of "Cannot call method 'is_ancestor_of' on a null value." errors from Godot. Unroll the one liner to add the parent null check and use some intermediate variables to remove duplicate method calls. Note that the is_inside_tree() call is dropped since it's redundant to checking if get_tree() returns null.

Util: Make node_is_part_of_edited_scene safer

---

addons/block_code/ui/blocks/block/block.gd

The bottom_snap must be set on ready, regardless of previously setting it.
Regression from 9aae2bb6
Fixes: #172

Block: Set bottom_snap_path when ready

---

addons/block_code/ui/block_canvas/block_canvas.gd

By simply assigning it to the scene resource property when loading the tree.
Follow up of 01ab76c5 which already removed all resource regeneration except when loading the canvas.

Block Canvas: Reuse saved block scene resource

---

addons/block_code/ui/picker/categories/category_factory.gd

If a space is left in the Y axis, the default doesn't work. This fixes a bug where focusing the Y side of a Vector2 input and then losing the focus ends with the " " string in the input, losing the default number.
Follow up of https://github.com/endlessm/godot-block-coding/pull/160
https://phabricator.endlessm.com/T35562

Parameter input: Fix Vector2 split

---

addons/block_code/drag_manager/drag.gd
addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/control_block/control_block.tscn
addons/block_code/ui/blocks/utilities/background/background.gd
addons/block_code/ui/blocks/utilities/background/gutter.gd

Instead of reusing the background.gd script to draw a gutter in ControlBlock, define a new script (gutter.gd) specifically for that purpose. In the existing background.gd script, draw a left border which is expected to flow into the gutter if shift_top or shift_bottom is set.
https://phabricator.endlessm.com/T35538

Improve ControlBlock background drawing

---

addons/block_code/drag_manager/drag.gd
addons/block_code/drag_manager/drag_manager.gd
addons/block_code/ui/block_tree_util.gd
addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/blocks/control_block/control_block.tscn
addons/block_code/ui/blocks/entry_block/entry_block.tscn
addons/block_code/ui/blocks/parameter_block/parameter_block.gd
addons/block_code/ui/blocks/parameter_block/parameter_block.tscn
addons/block_code/ui/blocks/statement_block/statement_block.tscn
addons/block_code/ui/blocks/utilities/background/background.gd
addons/block_code/ui/blocks/utilities/background/gutter.gd
addons/block_code/ui/blocks/utilities/snap_point/snap_point.gd
addons/block_code/ui/constants.gd
addons/block_code/ui/picker/picker.gd

Allow a Block to be deleted with a confirmation dialog when the Delete
key is pressed. However, when the Block is in the picker (rather than
the canvas), it shouldn't be deleted. Add a flag to disable deleting and
restore it when a drag completes. Furthermore, when it shouldn't be
deleted, stop propagating the Delete key so it doesn't try to delete the
whole BlockCode node.
Fixes: #162

Block: Allow deleting with Delete button

---

addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/block_canvas/block_canvas.tscn

For https://github.com/endlessm/godot-block-coding/issues/186, this adds a feature which resets the editor zoom level and scroll position when the user clicks the zoom label (now button) in the bottom right corner. This is consistent with the zoom button in Godot's 2D editor, although for our purpose I felt better about _always_ resetting the scroll position.
For https://github.com/endlessm/godot-block-coding/issues/187, this changes the zoom label to use `CanvasItem.modulate` instead of overriding the text colour.

Zoom label enhancements

---

addons/block_code/ui/picker/categories/category_factory.gd

According to the discussion [1], add the sound blocks into function `get_built_in_blocks()`'s class matching. It generates blocks belonging to AudioStreamPlayer node, including setting the property's value.
Therfore, we have sound blocks in both types of general script and GDScript flavor.
[1]: https://github.com/endlessm/godot-block-coding/pull/161#discussion_r1692961580
https://phabricator.endlessm.com/T35609

category_factory: Add another Sounds blocks for GDScript flavor

---

addons/block_code/blocks/lifecycle/physics_process.tres
addons/block_code/blocks/lifecycle/process.tres
addons/block_code/blocks/lifecycle/ready.tres
addons/block_code/blocks/log/print.tres
addons/block_code/blocks/loops/for.tres
addons/block_code/blocks/loops/while.tres
addons/block_code/code_generation/block_definition.gd
addons/block_code/code_generation/blocks_catalog.gd
addons/block_code/code_generation/util.gd
addons/block_code/examples/pong_game/pong_game.tscn
addons/block_code/serialization/default_block_script.tres
addons/block_code/ui/picker/categories/category_factory.gd
addons/block_code/ui/util.gd
tests/test_instruction_tree.gd

Taking as reference commits from #147 
Notable changes:
- The loading occurs in the new block catalog, not in the UI.
- Changed the file matching to use case-insensitive "globbing".
- Sync'ing things like tooltips (description field) that have been updated in main.
https://phabricator.endlessm.com/T35591

T35591 Read block definition from resource files

---

addons/block_code/blocks/math/randf_range.tres
addons/block_code/blocks/math/randi_range.tres
addons/block_code/ui/picker/categories/category_factory.gd

Add 4 random number generation blocks.
One for each of these godot's functions:
1. [`randi`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-randi)
2. `randi_range(from,to)`
3. `randf`
4. `randf_range(from,to)`

Add 4 random number generation blocks

---

addons/block_code/block_code_plugin.gd

Previously, it was possible for _selected_block_code to refer to an object which had been freed, which resulted in an error when calling disconnect for its signals.

Check _selected_block_code is still valid before disconnecting

---

addons/block_code/blocks/communication/area2d_on_exited.tres

The signal needs to be body_exited.

Fix signal name for area2d_on_exited block

---

addons/block_code/simple_nodes/simple_character/simple_character.gd
addons/block_code/simple_nodes/simple_scoring/simple_scoring.gd

There is no need for this cleanup because from docs: [1]
> If the node has children, its _exit_tree callback will be called last,
> after all its children have left the tree.
Also because: [2]
> when a node is freed with Object.free or queue_free, it will also free
> all its children.
Further, this removes the sprite and collision while in the editor when the user switches to another scene tab #213.
[1] https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-private-method-exit-tree
[2] https://docs.godotengine.org/en/stable/classes/class_node.html#description
Fixes #213

Remove _exit_tree methods from Simple nodes

---

addons/block_code/simple_nodes/simple_character/simple_character.gd
addons/block_code/simple_nodes/simple_scoring/simple_scoring.gd

Change the logic so there is no fallback 100x100 collision shape if a
texture is not provided. This way the user can customize their character
by adding their own sprites and collision shapes as node children. The
simple setup of passing a texture is still maintained. Although it has
been found to be inflexible (can't resize the texture from the canvas,
can't change the shape of the collision).
Addresses https://github.com/endlessm/godot-block-coding/issues/215

SimpleCharacter: Don't impose a collision shape

---

addons/block_code/blocks/input/characterbody2d_is_on_floor.tres
addons/block_code/code_generation/blocks_catalog.gd
addons/block_code/simple_nodes/simple_character/simple_character.gd

Add ways to check different states of the character, so a platformer character can have different assets / animations when jumping / moving / being idle.
Example video:
[Grabación de pantalla desde 2024-09-10 15-04-11.webm](https://github.com/user-attachments/assets/e6e235e9-9c6f-4666-b677-be66f5a9aea7)
That is using these blocks:

Add character states

---

addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd

Option inputs only allow selecting from a set of predefined OptionData values. Prevent trying to snap a block to an option input by making the snap point invisible.
Fixes: #167
Note that this doesn't fix the more general problem that the comparison block can't handle vectors, but I think it fixes the more important issue that you could snap a block into options.

ParameterInput: Don't snap blocks for option inputs

---

addons/block_code/ui/picker/categories/variable_category/create_variable_button.gd
addons/block_code/ui/picker/categories/variable_category/create_variable_dialog.gd
addons/block_code/ui/picker/categories/variable_category/create_variable_dialog.tscn

When the dialog is focused, we need to focus the custom dialog's own controls instead of the dialog's buttons. In addition, set focus_next and focus_previous properties so focus flows between child widgets and the dialog's ok / cancel buttons. The focus loops around within the dialog, as is conventional with other dialogs in the Godot editor.

Improve keyboard accessibility in create_variable_dialog

---

addons/block_code/blocks/log/breakpoint.tres

An example of this in use:
We can't see the generated code in the debugger (or at least I don't know how to reach it), but we can inspect local variables and the Godot objects they are referencing, which can be fairly useful.

Add breakpoint block

---

addons/block_code/blocks/input/is_input_actioned.gd
addons/block_code/blocks/input/is_input_actioned.tres
addons/block_code/code_generation/blocks_catalog.gd

This adds a block extension script to generate an options list instead of `BlocksCatalog._get_inputmap_actions`.

Add is_input_actioned.tres

---

addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/statement_block/statement_block.gd
addons/block_code/ui/blocks/utilities/parameter_output/parameter_output.gd
addons/block_code/ui/blocks/utilities/parameter_output/parameter_output.tscn

Found these while chasing the following error:
```
ERROR: res://addons/block_code/ui/blocks/utilities/parameter_output/parameter_output.tscn:30 - Parse Error: [ext_resource] referenced non-existent resource at: res://addons/block_code/ui/blocks/utilities/snap_point/snap_point.tscn
at: _parse_ext_resource (scene/resources/resource_format_text.cpp:159)
```
The message is deeply unhelpful, but it's caused by a circular dependency between classes.

Cleanup dependencies

---

addons/block_code/block_code_plugin.gd
addons/block_code/blocks/communication/get_node.gd
addons/block_code/blocks/communication/get_node.tres
addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/block_canvas/block_canvas.tscn
addons/block_code/ui/constants.gd
addons/block_code/ui/main_panel.gd
addons/block_code/ui/title_bar/title_bar.gd
addons/block_code/ui/util.gd
tests/test_category_factory.gd

In order to call methods on other nodes, you need a reference to the node. This adds a new `get_node` block definition that has all the other nodes provided as options. It also adds a method to drag a node from the scene tree dock and set the node's path in a `get_node` block automatically.
Unfortunately, in order to make the drag action usable, I had to drop the multi-select feature that automatically activates the block node's parent in the scene editor. I searched long for a way to do that without selecting the node, but it doesn't appear that there's a way to do it.
https://phabricator.endlessm.com/T35648

Allow dragging nodes to block canvas

---

addons/block_code/examples/spawner/ball.tscn
addons/block_code/examples/spawner/spawner.tscn
addons/block_code/examples/spawner/volatile_ball.tscn
addons/block_code/simple_spawner/simple_spawner.gd
addons/block_code/ui/constants.gd

This is a node with blocks to simplify the instantiation of other scenes and adding them to the current one.
Instantiated scenes are added as children of the SimpleSpawner node, so their position, ordering, etc, is relative to this node.
Blocks are provided to spawn once and to start / stop spawning based on a frequency.
Multiple scenes can be provided to be instantiated. In which case one is randomly picked when spawning.
For performance concerns, the amount of instantiated scenes is limited by default, unless the learner sets the limit to be zero (unlimited).
There are 2 behaviors to choose for when the limit is reached:
- Replace: Remove the oldest spawned scene and spawn a new one.
- No Spawn: No spawn happens until any spawned scene is removed by other means. …

Add SimpleSpawner node and blocks

---

addons/block_code/ui/blocks/block/block.gd

Increase the z_index of the focused block's content, but decrease the z_index of its snap areas. This ensures that the focused block is completely in view, including its outline.

Block: Set z_index on focus

---

addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/control_block/control_block.tscn
addons/block_code/ui/blocks/entry_block/entry_block.tscn
addons/block_code/ui/blocks/parameter_block/parameter_block.gd
addons/block_code/ui/blocks/parameter_block/parameter_block.tscn
addons/block_code/ui/blocks/statement_block/statement_block.gd
addons/block_code/ui/blocks/statement_block/statement_block.tscn
addons/block_code/ui/blocks/utilities/drag_drop_area/drag_drop_area.gd
addons/block_code/ui/blocks/utilities/drag_drop_area/drag_drop_area.tscn
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.tscn

Instead of using only _input to process events, use _gui_input to watch for mouse button events that are understood to be for an input control, but use _input to watch for mouse movement events which may occur outside of the control.
To work within the rules of Godot's GUI event system, we need to do this in a control which is a child of each input control. This is achieved using draggable_overlay.tscn.

ParameterInput: Ignore mouse events when not visible

---

addons/block_code/examples/pong_game/pong_game.tscn

Instead of setting a group for the "SimpleScoring" node, use the new call_method_node block.

Pong: Use call method in node

---

addons/block_code/ui/blocks/block/block.gd

Prior to commit 7a6fe1329cb2d2b746a08fedb3fb6288cc0e6bba, instantiate_block() would set the new Block's tooltip_text property to the BlockDefinition's description.
Since that commit, we just set a definition property on the Block to the BlockDefinition.
Implement Control._get_tooltip(), returning BlockDefinition.definition, which restores tooltips to blocks.
https://phabricator.endlessm.com/T35645

block: Show tooltips for blocks

---

addons/block_code/drag_manager/drag_manager.gd
addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/parameter_block/parameter_block.gd
addons/block_code/ui/blocks/statement_block/statement_block.gd
addons/block_code/ui/blocks/utilities/drag_drop_area/drag_drop_area.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/blocks/utilities/parameter_output/parameter_output.gd
addons/block_code/ui/blocks/utilities/template_editor/template_editor.gd
addons/block_code/ui/picker/categories/block_category_display.gd
addons/block_code/ui/picker/picker.gd

In DragManager, use the offset to ensure the block being dragged is
positioned under the cursor based on where the user started dragging.
-----
Based on #236.

DragDropArea: Add offset to drag_started signal

---

addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/blocks/utilities/drag_drop_area/drag_drop_area.gd

Use the _gui_input virtual function to pan and zoom the block canvas, instead of _input. This way, events are filtered according to the block canvas's visibility. As a side-effect, the block canvas processes input events after any containing widgets. For example, middle clicking inside a parameter input component will no longer begin panning. However, this is a better situation than the block canvas handling input events regardless of its visibility.
Closes: https://github.com/endlessm/godot-block-coding/issues/184

BlockCanvas: Use _gui_input instead of _input

---

addons/block_code/simple_spawner/simple_spawner.gd

With Godot 4.3, it is possible to use is_instance_valid as a Callable. To support Godot 4.2.2, we must use an anonymous function instead.

Fix error in simple_spawner.gd with Godot 4.2.2

---

addons/block_code/blocks/communication/add_node_to_group.tres
addons/block_code/blocks/communication/add_to_group.tres
addons/block_code/blocks/communication/call_method_group.tres
addons/block_code/blocks/communication/groups.gd
addons/block_code/blocks/communication/is_in_group.tres
addons/block_code/blocks/communication/is_node_in_group.tres
addons/block_code/blocks/communication/remove_from_group.tres
addons/block_code/blocks/communication/remove_node_from_group.tres
addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/picker/categories/block_category_display.gd

Several blocks work with node groups. Rather than having the user enter the group, offer the current groups as options. This is trickier than expected since Godot offers no API to get the current groups. Finding them involves 2 parts:
* Get scene local groups by calling get_groups() on each node in the scene.
* Get project global groups (starting in 4.3) by getting the `global_group` values in the project settings.
Monitoring for changes to the global groups is possible by listening for project settings changes. Monitoring for local group changes is not possible since the only events that occur are internal to Godot and not available in GDScript.
https://phabricator.endlessm.com/T35647
This is a naive implementation. The groups are specific to the scene and project. Rather than have each …

blocks: Add groups option block extension

---

addons/block_code/blocks/communication/add_node_to_group.tres
addons/block_code/blocks/communication/add_to_group.tres
addons/block_code/blocks/communication/call_method_group.tres
addons/block_code/blocks/communication/is_in_group.tres
addons/block_code/blocks/communication/is_node_in_group.tres
addons/block_code/blocks/communication/remove_from_group.tres

This spares us some grief in the code templates for different group-related blocks.
https://phabricator.endlessm.com/T35647

blocks: Use string type for group names

---

addons/block_code/simple_spawner/simple_spawner.gd

In the current implementation, spawned nodes are children of the spawner. In some cases this behaviour is what you want, but it means it's not possible to change the spawn position of future scenes without moving already-spawned scenes.
Add a new property to SimpleSpawner which allows choosing a new mode where spawned scenes are made children of the root scene.
The change in spawn_start() is necessary because, if the Start Spawning block is used in the On Ready entrypoint, this results in spawn_start() being called from the SimpleSpawner's _ready() function. At this point, the SimpleSpawner itself is ready but the root scene is not. In this case, attempting to add a child to the root scene logs an error, and a later attempt to get the spawned scene's parent to remove it returns undefined.

SimpleSpawner: Allow spawning nodes as child of scene

---

addons/block_code/examples/pong_game/player_score.tscn
addons/block_code/examples/pong_game/pong_game.tscn
addons/block_code/simple_nodes/simple_scoring/simple_scoring.gd

Instead of SimpleScoring providing a left and right score, change it to keep track of a single score, and show a single label. In the pong_game scene, we add two nodes: one for the left player, one for the right player.

simple_scoring: Show a single score label

---

addons/block_code/types/types.gd

A vector is truthy if either component is non-zero, and falsey if both components are zero.

Allow using Vector2 in boolean context

---

addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.tscn

Changes the text color and style of the dropdowns to have no mouse hover interaction and more contrast. The dropdown popup menu is unaffected (it will still use the editor theme)
Fixes #203

Dropdown contrast

---

addons/block_code/ui/util.gd

Cuurently, it prepends the "/root/" to the node's name as the path, if the node is the scene's root node. But, the absolute path reference points to nothing and leads NULL accessment. So, do not reform the path for the root node of the scene.

Util: Fix getting sub-scene's root path

---

addons/block_code/blocks/graphics/animationplayer_play.tres

Add an option for playing the animation and waiting until it's done. The previous behavior is now another option "play in the background".
For editing these block definition options in the Inspector, the class name is back to OptionData.

Await until animation is finished

---

addons/block_code/blocks/lifecycle/queue_free_node.tres

When spawning nodes with SimpleSpawner, you likely need a way to delete the node eventually. While you can call queue_free on a node using the call_method_node block, it's nicer to hide the queue_free detail behind a block.

blocks: Add remove node block

---

addons/block_code/ui/main_panel.gd

This fixes an issue where the blocks picker incorrectly generates its list of blocks before the block code node's block script is ready.

block_canvas: Select the new block code node in add block code

---

addons/block_code/blocks/communication/area2d_on_entered.tres
addons/block_code/blocks/communication/area2d_on_exited.tres
addons/block_code/blocks/communication/rigidbody2d_on_entered.tres
addons/block_code/blocks/communication/rigidbody2d_on_exited.tres
tests/test_code_generation.gd

Entry blocks already add a trailing newline, so there's no need to include one in the code template. See the ready, process and define_method blocks, for example. Having one doesn't cause any harm, but it does make the generated code uglier.

blocks: Remove extra newlines from entry blocks

---

addons/block_code/drag_manager/drag.gd

Applies scale to preview block
Before:
After:

Scale preview block

---

addons/block_code/simple_nodes/simple_ending/simple_ending.gd
addons/block_code/ui/constants.gd

This provides a label that displays either a win or lose message along with blocks to set or clear the label during the game. Label is inherited directly so that all the label properties are available in the inspector.
https://phabricator.endlessm.com/T35661

simple_nodes: Add SimpleEnding node

---

addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/block_canvas/block_canvas.tscn

Adds zoom in and out buttons for touch input devices

Zoom in and out buttons

---

addons/block_code/block_code_plugin.gd
addons/block_code/ui/script_window/script_window.gd
addons/block_code/ui/script_window/script_window.tscn

Here is how it looks now with dark and light themes:

Fix script popup

---

addons/block_code/ui/blocks/block/block.gd

The variant name as a string is appended to the description. If null, then no type is shown
Helping with https://github.com/endlessm/godot-block-coding/issues/271#issue-2583897016

Include type in tooltip

---

addons/block_code/examples/spawner/spawner.tscn
addons/block_code/simple_spawner/simple_spawner.gd

This property is the time, in seconds, to wait between spawning scenes. This is a period/interval/wavelength, not a frequency, which would be measured in Hz, or 1/seconds.
Adjust the name of the property and its documentation.
The instances of “frequency” that I have not changed are in the example scene's on-screen documentation. In this case it was actually used correctly: the keyboard action to increase the frequency reduces the property which is now called period, and the decrease action respectively increases the period.
I also added an annotation I learned yesterday to put units in the inspector slider for spawn period and spawn limit.

SimpleSpawner: Rename frequency to period

---

addons/block_code/serialization/block_serialization.gd
addons/block_code/serialization/value_block_serialization.gd
addons/block_code/simple_spawner/simple_spawner.gd
tests/data/simple_spawner_compat.tscn
tests/test_compatibility.gd

This adds handling for the SimpleSpawner compatibility breakage in #272. While I don't expect it to significantly affect our users, I took it as a chance to investigate how these issues could be handled. It shows how to handle a renamed property and a renamed block. I added everyone as reviewers to see what I came up with.
The added test validates the migration, but you can also see it for yourself by loading the `res://tests/data/simple_spawner_compat.tscn` scene in the editor. It should show that the scene is unsaved. After saving you'll see the names in the scene file have been updated appropriately.
https://phabricator.endlessm.com/T35547

Handle SimpleSpawner compatibility

---

addons/block_code/code_generation/blocks_catalog.gd

In commit c18ab3f we regressed the property names from capitalized to lower case. We actually want both: capitalize them and then lower case them.
Fixes https://github.com/endlessm/godot-block-coding/issues/302

Switch property labels back to human readable

---

addons/block_code/ui/block_canvas/block_canvas.gd

Dragging the node's property from Inspector shows the object's type as "obj_property". So, allow the "obj_property" type in _can_drop_data() and handle it in _drop_data(). Then, implement getting the property's value as a Variable block with _drop_obj_property() in detail.
And, if the modifier CTRL key is pressed, then drop a setting the property's value block.
https://phabricator.endlessm.com/T35649

BlockCanvas: Implement drag & drop the node's property from Inspector

---

.tx/config
addons/block_code/README.md

This adds configuration for the tx client and a pointer to the project. Later we might make use of the full Transifex/GitHub integration[1].
1. https://help.transifex.com/en/articles/6265125-github-installation-and-configuration
https://phabricator.endlessm.com/T35709

Initial Transifex configuratoin

---

addons/block_code/README.md

Add how to drag & drop node's property as getter & setter blocks from the Inspector dock.
This follows #296.
https://phabricator.endlessm.com/T35649

README: Add info of drag & drop node's property from Inspector

---

addons/block_code/blocks/communication/switch_scene.tres

Add a new block that allows the user to switch to another scene via a specified scene file path.
https://phabricator.endlessm.com/T35706

Add switch_scene resource

---

addons/block_code/README.md
scripts/godot.sh
scripts/merge-messages.sh
scripts/regenerate-pot.gd
scripts/regenerate-pot.sh
scripts/update-pot-files.gd
scripts/update-pot-files.sh

CLI script for updating translations. The `regenerate-pot.gd` script is pretty nasty since it has to with for the editor before poking at the UI. The others are pretty straightforward. I wasn't sure if we wanted to add GitHub workflows for these or not.
https://phabricator.endlessm.com/T35705

Translation scripts

---

addons/block_code/ui/blocks/block/block.gd

In commit 3e208d75ccb761d936b3126082407632dc09d7ec, the string "Type:" was extracted from the template string to be translated separately, including The colon. It is correct for the colon to be part of the translatable string, because (for example) in French there must be a non-breaking space between the word and the colon.
However, there was also a stray colon in the template string. Remove it.

Fix "Type::" double colon in block tooltip

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue.yml

This is an open-source plugin and now also developed in the open. Remove link to Endless Employees issue tracker. Edit the "public" template to be the sole issue template.

Update GitHub issue templates

---

addons/block_code/block_code_node/block_code.gd
addons/block_code/code_generation/blocks_catalog.gd
addons/block_code/serialization/block_script_serialization.gd
addons/block_code/ui/block_canvas/block_canvas.gd

The drag & drop object property's blocks disappear after save & re-open the Godot project. And, shows error:
core/variant/variant_utility.cpp:1092 - Cannot construct block from null block definition. res://addons/block_code/ui/block_canvas/block_canvas.gd:348 - Invalid call. Nonexistent function 'set_parameter_values_on_ready' in base 'Nil'.
It is because the object property blocks are not the predefined blocks in the catalog. So, Block Coding plugin cannot find the block definition from the catalog when places the object property blocks into the cavas via _block_to_ast_node() after re-open the project.
Therefore, introduce _get_obj_property_block_definition() generating object property's getter/setter block definition for get_block_definition(). Besides, it also needs the object …

BlockScriptSerialization: Re-generate block definition for object property blocks

---

addons/block_code/ui/blocks/control_block/control_block.gd
addons/block_code/ui/blocks/control_block/control_block.tscn
addons/block_code/ui/blocks/entry_block/entry_block.tscn
addons/block_code/ui/blocks/statement_block/statement_block.gd
addons/block_code/ui/blocks/statement_block/statement_block.tscn
addons/block_code/ui/blocks/utilities/background/background.gd

This is a refactor of the block background which has different shapes for the different block types. To make the work in #273 easier to rebase.

Shapes refactor

---

addons/gut/fonts/AnonymousPro-Bold.ttf.import
addons/gut/fonts/AnonymousPro-BoldItalic.ttf.import
addons/gut/fonts/AnonymousPro-Italic.ttf.import
addons/gut/fonts/AnonymousPro-Regular.ttf.import
addons/gut/fonts/CourierPrime-Bold.ttf.import
addons/gut/fonts/CourierPrime-BoldItalic.ttf.import
addons/gut/fonts/CourierPrime-Italic.ttf.import
addons/gut/fonts/CourierPrime-Regular.ttf.import
addons/gut/fonts/LobsterTwo-Bold.ttf.import
addons/gut/fonts/LobsterTwo-BoldItalic.ttf.import
addons/gut/fonts/LobsterTwo-Italic.ttf.import
addons/gut/fonts/LobsterTwo-Regular.ttf.import

Working with the project, these files in the Gut addon change to what's currently being commited. This is because Godot 4.3 adds `disable_embedded_bitmaps=true`
in font file imports. We did this already in 68522f84 but then in 31b09aa9 we updated Gut to 9.3.0. I guess we'll keep doing it until the issue is fixed upstream. Issue opened upstream:
https://github.com/bitwes/Gut/issues/673

Update Gut import files for Godot 4.3

---

addons/block_code/code_generation/block_definition.gd
addons/block_code/code_generation/blocks_catalog.gd
addons/block_code/serialization/block_script_serialization.gd
addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/blocks/utilities/template_editor/template_editor.gd

Dragging the files from resource FileSystem shows the files' type as
"files". So, allow the "files" type in _can_drop_data() and handle it in
_drop_data(). Then, implement getting the files' resource paths as
Variable blocks with _drop_files() in detail.
https://phabricator.endlessm.com/T35712

BlockCanvas: Implement drag & drop the file from resource FileSystem

---

addons/block_code/examples/pong_game/pong_game.tscn

Done by using the new feature, dragging the sound resources from the Filesystem dock to the block canvas.
The diff is crazy because resource IDs change all the time, but this is what it looks like now:

Pong example: Use blocks for sound resources

---

addons/block_code/ui/blocks/utilities/background/background.gd

The "is_pointy_value" property depends on the block type to be Value. And the "control_part" property depends on the block type to be Control.
[Grabación de pantalla desde 2024-12-06 15-24-47.webm](https://github.com/user-attachments/assets/3af886c0-c389-4c28-a8f0-d2a1b50ee7db)

Background: Disable/enable conditional properties

---

addons/block_code/README.md

Add how to drag & drop a resource file as getter block from the Resource Filesystem dock.
This follows https://github.com/endlessm/godot-block-coding/pull/305.
https://phabricator.endlessm.com/T35712

README: Add info of drag & drop a file from Resource Filesystem

---

addons/block_code/code_generation/block_definition.gd
addons/block_code/ui/main_panel.gd
addons/block_code/ui/main_panel.tscn
addons/block_code/ui/picker/picker.gd

/claim #282 
- adds a checkbox to the main_panel title bar
- adds `is_advanced` boolean to the block_definition (default value is false)
- hides advanced blocks when the checkbox is not ticked.

Added advanced mode

---

addons/block_code/simple_nodes/simple_character/simple_character.gd

/claim #257 
I added some Input Actions to the InputMap so that `player_1_up` contains both keyboard and controller events.
Player 1 and Player 2 joystick buttons are identical aside from belonging to different devices. (Player 1 = Device 0 and Player 2 = Device 1)

Added controller support for move block

---

addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/blocks/utilities/drag_drop_area/drag_drop_area.gd

Add a context menu with duplicate and delete options. Delete was previously only available from a Del shortcut.
Duplicate affects snapped blocks. The context menu is displayed when the canvas receives a mouse right click.
Fixes https://github.com/endlessm/godot-block-coding/issues/201

Add Duplicate blocks functionality

---

addons/block_code/simple_nodes/simple_character/simple_character.gd

Previously this description claimed that x is vertical and y horizontal.
Fix this, and clarify some other terms.

SimpleCharacter: Fix axis confusion in tooltip

---

.github/workflows/checks.yaml
addons/block_code/simple_spawner/simple_spawner.gd
addons/block_code/ui/block_canvas/block_canvas.gd
addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/picker/categories/block_category_button.gd
addons/block_code/ui/tooltip/tooltip.gd
addons/block_code/ui/util.gd
asset-template.json.hb

Godot 4.3 has been available for 4 months and it seems unlikely that anyone will have a pressing need to add blocks to a Godot 4.2 project.
Although we have been running unit tests against 4.2 in CI, those do not cover the full functionality of the plugin. To the best of my knowledge, no-one is regularly testing the plugin interactively against Godot 4.2.
Set the minimum version in the asset library template. Drop 4.2 from the CI test matrix. Remove some workarounds for 4.2 compatibility.

Set Godot 4.3 as minimum supported version

---

addons/block_code/blocks/communication/groups.gd

There was one pending reference to the polyfill. Fixup for commit 0525fbe0cfcce133ed52aa0b34de0e70deb38c38

Fix remove polyfill for Node.is_part_of_edited_scene()

---

.github/workflows/checks.yaml

This is potentially interesting because we have translation-related code
that behaves differently between 4.4 (which has some new API) and older
versions (which do not).

Run tests with Godot 4.4 prerelease

---

addons/block_code/README.md

We've had multiple users mention that they'd like a better way to share ideas, comments and questions.
Discord is one option but I think given current activity levels we'd be better served by a less synchronous option.
I've enabled GitHub Discussions as a test. Point users there.

Point to Discussions board for feedback and support

---

addons/block_code/block_code_node/block_code.gd

Add a warning when the parent node of a BlockCoding node already has a script. To inform the user.
Fix https://github.com/endlessm/godot-block-coding/issues/356

Warn when Block Code overrides parent script

---

addons/block_code/README.md

Addresses which Godot version a user should have installed (4.3 or newer)

Include minimum version in README

---

addons/block_code/block_code_node/block_code.gd

Commit 87c31b05c9f720cc2512285340117b86afc94e8e ("Warn when Block Code overrides parent script") introduced a warning when a BlockCode node's parent has a script attached. But if the parent is (for example) a Character2D with our SimpleCharacter script attached, this warning is incorrect: the block code script will correctly extend, not override, the parent.
Before issuing this warning, check if the parent's script has a class_name that matches what the generated BlockCode script will extend, and suppress the warning if so.
Fixes https://github.com/endlessm/godot-block-coding/issues/356

Don't warn when BlockCode script extends parent script

---

addons/block_code/drag_manager/drag_manager.gd
addons/block_code/ui/blocks/block/block.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.tscn
addons/block_code/ui/blocks/utilities/template_editor/template_editor.gd
addons/block_code/ui/blocks/utilities/template_editor/template_editor.tscn
addons/block_code/ui/picker/categories/block_category_display.gd

Add a new "editable" boolean property to Block, TemplateEditor and ParameterInput. When the block is in the picker, it will not be editable. Only when they are dragged to the canvas they become editable.
The property has to be in each of these components because Block can't access its ParameterInputs directly, only through its TemplateEditor.
The dropdown options in a not-editable block can still be changed to avoid disabling the button. But the change doesn't trigger any effect.
The default is editable = true, so blocks in the canvas are editable.
Fix https://github.com/endlessm/godot-block-coding/issues/357

Make blocks in Picker not editable

---

project.godot

This reverts the window stretch mode to what it was before a5444c59 . The Pong example is still the main scene, and the example can be cropped if this setting is the default.

Set window stretch mode to "canvas_items"

---

addons/block_code/ui/blocks/block/block.gd

The TranslationServer.get_or_add_domain() method was added in Godot 4.4, but the addon may still work in Godot 4.3 if we disable property translations when the method isn't present.
https://github.com/endlessm/godot-block-coding/discussions/397

Block: Translate property only if possible

---

addons/block_code/code_generation/block_definition.gd

Looks like a simple writing mistake!
Fix for https://github.com/endlessm/godot-block-coding/issues/400
Caused by [947bd28](https://github.com/endlessm/godot-block-coding/commit/947bd28888551a91fff86ee0ad0506eb27335109)

Repopulate variable code template
