endlessm/godot-block-coding

- addons/block_code/block_code_node/block_code.gd
- addons/block_code/block_code_node/utilities/signal_manager.gd
- addons/block_code/block_code_plugin.gd
- addons/block_code/simple_nodes/simple_character/simple_character.gd
- addons/block_code/ui/block_canvas/node_block_canvas/node_block_canvas.gd
- addons/block_code/ui/blocks/basic_block/basic_block.tscn
- addons/block_code/ui/blocks/control_block/control_block.tscn
- addons/block_code/ui/blocks/parameter_block/parameter_block.gd
- addons/block_code/ui/blocks/parameter_block/parameter_block.tscn
- addons/block_code/ui/blocks/statement_block/statement_block.tscn
- addons/block_code/ui/picker/categories/category_factory.gd
- project.godot
- test_game/test_game.tscn
This adds new blocks for signals. A node can broadcast a signal and any other node can receive it by name. Maybe can pass data through signals too. Added a physics process entry block, and simplified the movement block.
These are all steps towards making a simple game using blocks.
> New blocks: Signals, physics, and movement

- addons/block_code/drag_manager/drag_manager.gd
- addons/block_code/types/types.gd
- addons/block_code/ui/blocks/control_block/control_block.gd
- addons/block_code/ui/blocks/control_block/control_block.tscn
- addons/block_code/ui/blocks/parameter_block/parameter_block.tscn
- addons/block_code/ui/blocks/statement_block/statement_block.gd
- addons/block_code/ui/blocks/statement_block/statement_block.tscn
- addons/block_code/ui/blocks/utilities/background/background.gd
- addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
- addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.tscn
- addons/block_code/ui/picker/categories/category_factory.gd
Made it much easier to create new control blocks (if/else, loops), and styled them better.
Also added a way to create parameters in entry blocks, for example you could have an entry point if a body enters an Area2D, and the parameter would be the body entered (see new block in "test" category). Then maybe you could check the name of the body to increase the score or something. Conditional stuff will come next.
When implementing the "control" blocks, I did feel like generating a text script is a little messy, and would probably be cleaner with interpreted blocks. Maybe that is something to explore further, but for now I think this is working fine for a prototype, and we also want to possibly have a readable script for the user to switch to.
> Control and entry blocks with parameters

- addons/block_code/ui/blocks/control_block/control_block.gd
- addons/block_code/ui/blocks/utilities/background/background.gd
- addons/block_code/ui/constants.gd
https://phabricator.endlessm.com/T35477
> Outline UI

- addons/block_code/simple_nodes/simple_character/simple_character.gd
- addons/block_code/types/types.gd
- addons/block_code/ui/blocks/basic_block/basic_block.tscn
- addons/block_code/ui/blocks/control_block/control_block.gd
- addons/block_code/ui/blocks/parameter_block/parameter_block.gd
- addons/block_code/ui/blocks/parameter_block/parameter_block.tscn
- addons/block_code/ui/blocks/statement_block/statement_block.tscn
- addons/block_code/ui/blocks/utilities/background/background.gd
- addons/block_code/ui/picker/categories/category_factory.gd
- addons/block_code/ui/picker/picker.gd
- project.godot
- test_game/test_game.tscn
Demo project: Add input for 2 players
> 2 player input

- addons/block_code/ui/picker/categories/category_factory.gd
- test_game/test_game.tscn
These are user facing, so rename "cond" to "condition" and "num" to "number".
Also, use "not bool" instead of the deprecated "!bool" for the Not block.
> Block placeholders: improve wording

- docs/OVERVIEW.md
This adds a doc file that gives an overview of the flow of the program and explains the organization of the files.
Will add section for process of adding a new block.
https://phabricator.endlessm.com/T35448
> Add overview doc

- docs/OVERVIEW.md
Added some documentation to make the process and options for creating a new block clearer.
https://phabricator.endlessm.com/T35448
> Add create block documentation

- addons/block_code/types/types.gd
- addons/block_code/ui/block_canvas/option_data.gd
- addons/block_code/ui/blocks/utilities/parameter_input/parameter_input.gd
- addons/block_code/ui/picker/categories/category_factory.gd
Somehow I didn't catch this before, but the dropdowns weren't persisting because their data class wasn't getting serialized. Now it is a resource, and defined in it's own file with the other resources.
If someone wants to look this over one more time and make sure there are no bugs with the dropdowns that would be great.
https://phabricator.endlessm.com/T35505
> Quick fix: persist dropdowns

- addons/block_code/README.md
- Correct main heading
- Correct (and link to) EOSF
- Create a couple of more clear sections
- Consistently **bold** UI terms
- Consistent heading capitalization
- Link to tools that inspired us
- Add a sentence about learners familiarizing themselves with the Godot UI through our plugin
- Use the term "select" instead of "click" (minor nit, but is more inclusive of touch plus keyboard navigation—and more consistent with our OS docs)
> README: improve structure

- addons/block_code/examples/pong_game/pong_game.tscn
- project.godot
https://phabricator.endlessm.com/T35515
> Zero gravity

- addons/block_code/block_code_plugin.gd
The SimpleCharacter should be available in the node creation dialog box!
> Add simple character to node dialog

- addons/block_code/ui/picker/categories/category_factory.gd
https://phabricator.endlessm.com/T35529
> category_factory: Add tooltips into Lifecycle and Sounds blocks

- addons/block_code/ui/picker/categories/category_factory.gd
And add a "Move and slide" statement block so it can be used.
> Category factory: Expose CharacterBody2D velocity

- addons/block_code/drag_manager/drag_manager.gd
- addons/block_code/ui/blocks/parameter_block/parameter_block.gd
- addons/block_code/ui/blocks/utilities/parameter_output/parameter_output.gd
- addons/block_code/ui/blocks/utilities/snap_point/snap_point.gd
https://phabricator.endlessm.com/T35531
> Fix errors from duplicate output parameter blocks

- addons/block_code/ui/picker/picker.gd
[Screencast from 2024-07-03 14-01-29.webm](https://github.com/endlessm/godot-block-coding/assets/86760/a0b212c3-464c-4f75-9607-a66a8b659ab5)
> picker: Animate when scrolling to category

- addons/block_code/ui/blocks/utilities/background/background.gd
A couple of simplifications to building the shape of the background polygon.
I was looking at this code with an eye to fixing the left border of `if` blocks, but did not get to that yet. https://phabricator.endlessm.com/T35538
> Simplify background polygon

- addons/block_code/ui/blocks/block/block.gd
Once this is fixed in 4.3.
https://phabricator.endlessm.com/T35573
> Block: Add FIXME note for using SnapPoint directly

- addons/block_code/ui/picker/categories/category_factory.gd
"The following" was confusing to me; this makes it more clear by saying "Attached blocks"
> category_factory: Tweak tooltips

- addons/block_code/blocks/communication/call_method_node.tres
- addons/block_code/blocks/communication/define_method.tres
- addons/block_code/blocks/graphics/viewport_center.tres
- addons/block_code/blocks/graphics/viewport_height.tres
- addons/block_code/blocks/graphics/viewport_width.tres
- addons/block_code/blocks/logic/compare.tres
- addons/block_code/blocks/loops/await_scene_ready.tres
- addons/block_code/blocks/math/add.tres
- addons/block_code/blocks/math/divide.tres
- addons/block_code/blocks/math/multiply.tres
- addons/block_code/blocks/math/pow.tres
- addons/block_code/blocks/math/subtract.tres
- addons/block_code/blocks/sounds/load_sound.tres
- addons/block_code/blocks/sounds/pause_continue_sound.tres
- addons/block_code/blocks/sounds/play_sound.tres
- addons/block_code/blocks/sounds/stop_sound.tres
- addons/block_code/ui/blocks/control_block/control_block.gd
- addons/block_code/ui/blocks/parameter_block/parameter_block.gd
- addons/block_code/ui/picker/categories/category_factory.gd
- addons/block_code/ui/util.gd
This completes the port for blocks that don't depend on the node class.
Changes compared with #147:
- The definitions for sound, graphics and "await_scene_ready" blocks were missing.
- Added some missing defaults too.
https://phabricator.endlessm.com/T35591
> T35591 Add remaining general blocks

- .github/workflows/checks.yaml
- addons/gut/fonts/AnonymousPro-Bold.ttf.import
- addons/gut/fonts/AnonymousPro-BoldItalic.ttf.import
- addons/gut/fonts/AnonymousPro-Italic.ttf.import
- addons/gut/fonts/AnonymousPro-Regular.ttf.import
- addons/gut/fonts/CourierPrime-Bold.ttf.import
- addons/gut/fonts/CourierPrime-BoldItalic.ttf.import
- addons/gut/fonts/CourierPrime-Italic.ttf.import
- addons/gut/fonts/CourierPrime-Regular.ttf.import
- addons/gut/fonts/LobsterTwo-Bold.ttf.import
- addons/gut/fonts/LobsterTwo-BoldItalic.ttf.import
- addons/gut/fonts/LobsterTwo-Italic.ttf.import
- addons/gut/fonts/LobsterTwo-Regular.ttf.import
- project.godot
- tests/test_instruction_tree.gd
https://phabricator.endlessm.com/T35494
> Move development project to Godot 4.3

- addons/block_code/blocks/math/cos.tres
- addons/block_code/blocks/math/sin.tres
- addons/block_code/blocks/math/tan.tres
- addons/block_code/ui/picker/categories/category_factory.gd
Adds the following function
- `sin angle`
- `cos angle`
- `tan angle`
They all use _angle_ in degrees since I believe it is what most users are familiar with.
> Adds sin, cos and tan trigonometry function

- addons/block_code/blocks/graphics/viewport_center.tres
- addons/block_code/blocks/graphics/viewport_height.tres
- addons/block_code/blocks/graphics/viewport_width.tres
- addons/block_code/blocks/input/characterbody2d_move.tres
- addons/block_code/simple_nodes/simple_character/simple_character.gd
First pass at adding some missing tooltips.
https://phabricator.endlessm.com/T35563
> blocks: add viewport, simple_character, and characterbody2d_move tooltips

- addons/block_code/ui/constants.gd
The previous yellow didn't have enough contrast.
Fixes: #202
> Update Variables blocks color

- addons/block_code/locale/es.po
Run `tx pull --use-git-timestamps`. This brings a Spanish translation made by myself, and a partial German translation that's being contributed.
> Pull translations from Transifex

- addons/block_code/locale/pl.po
To the best of my knowledge no-one in the Endless team speaks Polish to review this. :)
> Add Polish translation from Transifex

- addons/block_code/README.md
This adds a Youtube video including preview
> Update README.md with Youtube link

- addons/block_code/blocks/lifecycle/physics_process.tres
And set it as an advanced block.
Fixes https://github.com/endlessm/godot-block-coding/issues/261
> Adds the every physics step block

- addons/block_code/blocks/communication/add_node_to_group.tres
- addons/block_code/blocks/communication/add_to_group.tres
- addons/block_code/blocks/communication/call_method_group.tres
- addons/block_code/blocks/communication/get_node.tres
- addons/block_code/blocks/communication/is_in_group.tres
- addons/block_code/blocks/communication/is_node_in_group.tres
- addons/block_code/blocks/communication/remove_from_group.tres
- addons/block_code/blocks/communication/remove_node_from_group.tres
- addons/block_code/blocks/graphics/animationplayer_play.tres
- addons/block_code/blocks/input/is_input_actioned.tres
- addons/block_code/blocks/logic/compare.tres
- addons/block_code/blocks/sounds/pause_continue_sound.tres
Godot does this automatically. Preventing the diff.
> Add is_advanced = false to non-advanced blocks
